### ISSUE TITLE
Desbordamiento del texto

### ISSUE THREAD

**Issue by nacholopex** [JaimeObregon/ladonacion.es#1]
Hola Jaime.
Me he fijado que al acceder a la página web desde mi navegador esta no muestra correctamente el texto principal de: `¿Qué hay detrás de esta extraña donación?`.

El problema parece ser que viene cuando la pantalla es de una anchura 1025 o superior, te adjunto una captura pantalla para que lo visualices.

![imagen](https://user-images.githubusercontent.com/24817636/191344343-7792115c-d62b-4ccb-92a2-7e8579542132.png)

**Comment by JaimeObregon** [comment]
¡Hola, @nacholopex! Muchas gracias por reportarlo ❤️.

En mis navegadores no he logrado reproducirlo; parece algo infrecuente relacionado quizá con la carga de la tipografía (en tu captura no parece haber cargado a tiempo).

Sea como fuere, he aplicado unos cambios sobre esa zona y ya no debería suceder.

Un abrazo.
